const galleryData = [
  {
    id: 'project-01',
    title: 'The Abstract Vision',
    slug: 'the-abstract-vision',
    image: ['/images/projects/project-01.jpg', '/images/projects/project-01.jpg', '/images/projects/project-01.jpg'],
    client: 'Self-initiated',
    year: '2025',
    tags: ['WebGL', 'Creative Dev', '3D'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-02',
    title: 'Digital Horizon',
    slug: 'digital-horizon',
    image: ['/images/projects/project-02.jpg', '/images/projects/project-02.jpg', '/images/projects/project-02.jpg'],
    client: 'Studio Kellmer',
    year: '2025',
    tags: ['Interactive', 'Motion', 'UI'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-03',
    title: 'Neon Dreams',
    slug: 'neon-dreams',
    image: ['/images/projects/project-03.jpg', '/images/projects/project-03.jpg', '/images/projects/project-03.jpg'],
    client: 'Personal',
    year: '2025',
    tags: ['Art', 'Shader', 'Generative'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-04',
    title: 'Fluid Mechanics',
    slug: 'fluid-mechanics',
    image: ['/images/projects/project-04.jpg', '/images/projects/project-04.jpg', '/images/projects/project-04.jpg'],
    client: 'Lab Project',
    year: '2024',
    tags: ['Physics', 'Simulation', 'WebGL'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-05',
    title: 'Minimal Orbit',
    slug: 'minimal-orbit',
    image: ['/images/projects/project-05.jpg', '/images/projects/project-05.jpg', '/images/projects/project-05.jpg'],
    client: 'Self-initiated',
    year: '2024',
    tags: ['Space', '3D', 'Minimal'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-06',
    title: 'Echoes in Time',
    slug: 'echoes-in-time',
    image: ['/images/projects/project-06.jpg', '/images/projects/project-06.jpg', '/images/projects/project-06.jpg'],
    client: 'Experimental',
    year: '2023',
    tags: ['Audio', 'Generative', 'Canvas'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-07',
    title: 'Quantum Flux',
    slug: 'quantum-flux',
    image: ['/images/projects/project-03.jpg', '/images/projects/project-03.jpg', '/images/projects/project-03.jpg'],
    client: 'Tech Innovations',
    year: '2022',
    tags: ['React', 'Data Visualization', 'D3.js'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-08',
    title: 'Synesthetic Beats',
    slug: 'synesthetic-beats',
    image: ['/images/projects/project-06.jpg', '/images/projects/project-06.jpg', '/images/projects/project-06.jpg'],
    client: 'Music Collective',
    year: '2022',
    tags: ['Audio', 'Interactive', 'GLSL'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-09',
    title: 'Prismatic Flow',
    slug: 'prismatic-flow',
    image: ['/images/projects/project-03.jpg', '/images/projects/project-03.jpg', '/images/projects/project-03.jpg'],
    client: 'Design Studio X',
    year: '2023',
    tags: ['Branding', 'Generative Art', 'Web'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-10',
    title: 'Infinite Loop',
    slug: 'infinite-loop',
    image: ['/images/projects/project-02.jpg', '/images/projects/project-02.jpg', '/images/projects/project-02.jpg'],
    client: 'Future Systems',
    year: '2021',
    tags: ['Creative Coding', 'Installation', '3D'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-11',
    title: 'Atmospheric Layers',
    slug: 'atmospheric-layers',
    image: ['/images/projects/project-01.jpg', '/images/projects/project-01.jpg', '/images/projects/project-01.jpg'],
    client: 'Nature Org',
    year: '2020',
    tags: ['Environmental', 'Interactive', 'Experience'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-12',
    title: 'Cellular Automata',
    slug: 'cellular-automata',
    image: ['/images/projects/project-06.jpg', '/images/projects/project-06.jpg', '/images/projects/project-06.jpg'],
    client: 'Academic Lab',
    year: '2020',
    tags: ['Math', 'Canvas2D', 'Algorithms'],
    url: 'https://www.google.com',
  },
  {
    id: 'project-13',
    title: 'Obsidian Dreams',
    slug: 'obsidian-dreams',
    image: ['/images/projects/project-04.jpg', '/images/projects/project-04.jpg', '/images/projects/project-04.jpg'],
    client: 'Modern Arts',
    year: '2020',
    tags: ['Contrast', 'Motion Design', 'Visuals'],
    url: 'https://www.google.com',
  },
]

export default galleryData
