import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "@/src/components/Header";
import Footer from "@/src/components/Footer";
import { TransitionProvider } from "@/src/context/TransitionContext";
import PageTransition from "@/src/components/PageTransition";
import SmoothScroll from "@/src/components/SmoothScroll";

const generalSans = localFont({
  src: [
    {
      path: '../../public/font/GeneralSans-Extralight.woff',
      weight: '200',
      style: 'normal',
    },
    {
      path: '../../public/font/GeneralSans-Light.woff',
      weight: '300',
      style: 'normal',  
    },
    {
      path: '../../public/font/GeneralSans-Regular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/font/GeneralSans-Medium.woff',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/font/GeneralSans-Semibold.woff',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/font/GeneralSans-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-generalSans',  // exposes as CSS variable
})

export const metadata: Metadata = {
  title: "Portfolio - Julian Kellmer",
  description: "Generated by Julian Kellmer - Portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={generalSans.variable}>
      <body className="antialiased">
        <TransitionProvider>
          <SmoothScroll>
            <Header />
            {children}
            <Footer />
            <PageTransition />
          </SmoothScroll>
        </TransitionProvider>
      </body>
    </html>
  );
}
